version: '3'

services:
  app:
    container_name: app
    build: ./
    volumes:
      - ./tmp/uploads/:/tmp/uploads/
      - ./:/app/
    expose:
      - "8000"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql_server
    depends_on:
      - mysql_server
    command: sh ./wait.sh mysql_server python3 app.py
    networks:
      - app-net

  web:
    container_name: web
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    restart: always
    privileged: true
    expose:
      - "80"
    ports:
      - "88:80"
    networks:
      - app-net

  mysql_server:
    image: mysql
    container_name: mysql_server
    restart: "always"
    expose:
      - "3306"
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_PORT: 3306
    networks:
      - app-net

networks:
  app-net:
    name: app-net
    driver: bridge